// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: ingestion.proto

package voiceintegrityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioChunkRequest represents a single audio frame/chunk streamed from
// the client (telecom switch, banking app, or API gateway).
type AudioChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique call session identifier
	CallSessionId string `protobuf:"bytes,1,opt,name=call_session_id,json=callSessionId,proto3" json:"call_session_id,omitempty"`
	// Tenant / organization identifier for rate limiting and billing
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Raw audio payload bytes (e.g. PCM 16-bit linear, Opus, or WAV)
	AudioBytes []byte `protobuf:"bytes,3,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	// Audio sample rate in Hz (default: 16000)
	SampleRateHz int32 `protobuf:"varint,4,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	// Audio channel count (default: 1 for mono)
	Channels int32 `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	// Monotonically increasing sequence number for this stream
	SequenceNumber int64 `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Client-side capture timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Flag indicating the end of the client's audio stream
	IsLastChunk bool `protobuf:"varint,8,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	// Known enrollment status of the claimed identity
	EnrollmentStatus EnrollmentStatus `protobuf:"varint,9,opt,name=enrollment_status,json=enrollmentStatus,proto3,enum=voiceintegrity.v1.EnrollmentStatus" json:"enrollment_status,omitempty"`
	// Optional contextual signal provided by client (e.g. device/geo risk)
	ContextualSignal *RiskSignal `protobuf:"bytes,10,opt,name=contextual_signal,json=contextualSignal,proto3" json:"contextual_signal,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AudioChunkRequest) Reset() {
	*x = AudioChunkRequest{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunkRequest) ProtoMessage() {}

func (x *AudioChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunkRequest.ProtoReflect.Descriptor instead.
func (*AudioChunkRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunkRequest) GetCallSessionId() string {
	if x != nil {
		return x.CallSessionId
	}
	return ""
}

func (x *AudioChunkRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AudioChunkRequest) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *AudioChunkRequest) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *AudioChunkRequest) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunkRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AudioChunkRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AudioChunkRequest) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *AudioChunkRequest) GetEnrollmentStatus() EnrollmentStatus {
	if x != nil {
		return x.EnrollmentStatus
	}
	return EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED
}

func (x *AudioChunkRequest) GetContextualSignal() *RiskSignal {
	if x != nil {
		return x.ContextualSignal
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\x11voiceintegrity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15risk_assessment.proto\"\xe0\x03\n" +
	"\x11AudioChunkRequest\x12&\n" +
	"\x0fcall_session_id\x18\x01 \x01(\tR\rcallSessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vaudio_bytes\x18\x03 \x01(\fR\n" +
	"audioBytes\x12$\n" +
	"\x0esample_rate_hz\x18\x04 \x01(\x05R\fsampleRateHz\x12\x1a\n" +
	"\bchannels\x18\x05 \x01(\x05R\bchannels\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x03R\x0esequenceNumber\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\"\n" +
	"\ris_last_chunk\x18\b \x01(\bR\visLastChunk\x12P\n" +
	"\x11enrollment_status\x18\t \x01(\x0e2#.voiceintegrity.v1.EnrollmentStatusR\x10enrollmentStatus\x12J\n" +
	"\x11contextual_signal\x18\n" +
	" \x01(\v2\x1d.voiceintegrity.v1.RiskSignalR\x10contextualSignal\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"z\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xbf\x01\n" +
	"\x10IngestionGateway\x12b\n" +
	"\vStreamAudio\x12$.voiceintegrity.v1.AudioChunkRequest\x1a).voiceintegrity.v1.RiskAssessmentResponse(\x010\x01\x12G\n" +
	"\x04Ping\x12\x1e.voiceintegrity.v1.PingRequest\x1a\x1f.voiceintegrity.v1.PingResponseB$Z\"voiceintegrity/v1;voiceintegrityv1b\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ingestion_proto_goTypes = []any{
	(*AudioChunkRequest)(nil),      // 0: voiceintegrity.v1.AudioChunkRequest
	(*PingRequest)(nil),            // 1: voiceintegrity.v1.PingRequest
	(*PingResponse)(nil),           // 2: voiceintegrity.v1.PingResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(EnrollmentStatus)(0),          // 4: voiceintegrity.v1.EnrollmentStatus
	(*RiskSignal)(nil),             // 5: voiceintegrity.v1.RiskSignal
	(*RiskAssessmentResponse)(nil), // 6: voiceintegrity.v1.RiskAssessmentResponse
}
var file_ingestion_proto_depIdxs = []int32{
	3, // 0: voiceintegrity.v1.AudioChunkRequest.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: voiceintegrity.v1.AudioChunkRequest.enrollment_status:type_name -> voiceintegrity.v1.EnrollmentStatus
	5, // 2: voiceintegrity.v1.AudioChunkRequest.contextual_signal:type_name -> voiceintegrity.v1.RiskSignal
	3, // 3: voiceintegrity.v1.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: voiceintegrity.v1.IngestionGateway.StreamAudio:input_type -> voiceintegrity.v1.AudioChunkRequest
	1, // 5: voiceintegrity.v1.IngestionGateway.Ping:input_type -> voiceintegrity.v1.PingRequest
	6, // 6: voiceintegrity.v1.IngestionGateway.StreamAudio:output_type -> voiceintegrity.v1.RiskAssessmentResponse
	2, // 7: voiceintegrity.v1.IngestionGateway.Ping:output_type -> voiceintegrity.v1.PingResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	file_risk_assessment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
