// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: ingestion.proto

package voiceintegrityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionGateway_StreamAudio_FullMethodName = "/voiceintegrity.v1.IngestionGateway/StreamAudio"
	IngestionGateway_Ping_FullMethodName        = "/voiceintegrity.v1.IngestionGateway/Ping"
)

// IngestionGatewayClient is the client API for IngestionGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestionGateway handles high-throughput, low-latency audio streaming
// directly from client infrastructure into the Voice Integrity platform.
type IngestionGatewayClient interface {
	// Bidirectional streaming RPC: client continuously streams AudioChunkRequest,
	// service continuously streams dynamic RiskAssessmentResponse updates.
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunkRequest, RiskAssessmentResponse], error)
	// Health / ping RPC
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type ingestionGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionGatewayClient(cc grpc.ClientConnInterface) IngestionGatewayClient {
	return &ingestionGatewayClient{cc}
}

func (c *ingestionGatewayClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunkRequest, RiskAssessmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionGateway_ServiceDesc.Streams[0], IngestionGateway_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunkRequest, RiskAssessmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionGateway_StreamAudioClient = grpc.BidiStreamingClient[AudioChunkRequest, RiskAssessmentResponse]

func (c *ingestionGatewayClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, IngestionGateway_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestionGatewayServer is the server API for IngestionGateway service.
// All implementations must embed UnimplementedIngestionGatewayServer
// for forward compatibility.
//
// IngestionGateway handles high-throughput, low-latency audio streaming
// directly from client infrastructure into the Voice Integrity platform.
type IngestionGatewayServer interface {
	// Bidirectional streaming RPC: client continuously streams AudioChunkRequest,
	// service continuously streams dynamic RiskAssessmentResponse updates.
	StreamAudio(grpc.BidiStreamingServer[AudioChunkRequest, RiskAssessmentResponse]) error
	// Health / ping RPC
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedIngestionGatewayServer()
}

// UnimplementedIngestionGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionGatewayServer struct{}

func (UnimplementedIngestionGatewayServer) StreamAudio(grpc.BidiStreamingServer[AudioChunkRequest, RiskAssessmentResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedIngestionGatewayServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedIngestionGatewayServer) mustEmbedUnimplementedIngestionGatewayServer() {}
func (UnimplementedIngestionGatewayServer) testEmbeddedByValue()                          {}

// UnsafeIngestionGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionGatewayServer will
// result in compilation errors.
type UnsafeIngestionGatewayServer interface {
	mustEmbedUnimplementedIngestionGatewayServer()
}

func RegisterIngestionGatewayServer(s grpc.ServiceRegistrar, srv IngestionGatewayServer) {
	// If the following call panics, it indicates UnimplementedIngestionGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionGateway_ServiceDesc, srv)
}

func _IngestionGateway_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionGatewayServer).StreamAudio(&grpc.GenericServerStream[AudioChunkRequest, RiskAssessmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionGateway_StreamAudioServer = grpc.BidiStreamingServer[AudioChunkRequest, RiskAssessmentResponse]

func _IngestionGateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionGatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionGateway_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionGatewayServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestionGateway_ServiceDesc is the grpc.ServiceDesc for IngestionGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voiceintegrity.v1.IngestionGateway",
	HandlerType: (*IngestionGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _IngestionGateway_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _IngestionGateway_StreamAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ingestion.proto",
}
