// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: risk_assessment.proto

package voiceintegrityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentStatus int32

const (
	EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED EnrollmentStatus = 0
	EnrollmentStatus_NOT_ENROLLED                  EnrollmentStatus = 1
	EnrollmentStatus_ENROLLED                      EnrollmentStatus = 2
	EnrollmentStatus_ENROLLMENT_REVOKED            EnrollmentStatus = 3
)

// Enum value maps for EnrollmentStatus.
var (
	EnrollmentStatus_name = map[int32]string{
		0: "ENROLLMENT_STATUS_UNSPECIFIED",
		1: "NOT_ENROLLED",
		2: "ENROLLED",
		3: "ENROLLMENT_REVOKED",
	}
	EnrollmentStatus_value = map[string]int32{
		"ENROLLMENT_STATUS_UNSPECIFIED": 0,
		"NOT_ENROLLED":                  1,
		"ENROLLED":                      2,
		"ENROLLMENT_REVOKED":            3,
	}
)

func (x EnrollmentStatus) Enum() *EnrollmentStatus {
	p := new(EnrollmentStatus)
	*p = x
	return p
}

func (x EnrollmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_risk_assessment_proto_enumTypes[0].Descriptor()
}

func (EnrollmentStatus) Type() protoreflect.EnumType {
	return &file_risk_assessment_proto_enumTypes[0]
}

func (x EnrollmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentStatus.Descriptor instead.
func (EnrollmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_risk_assessment_proto_rawDescGZIP(), []int{0}
}

type RecommendedAction int32

const (
	RecommendedAction_ACTION_UNSPECIFIED              RecommendedAction = 0
	RecommendedAction_PROCEED                         RecommendedAction = 1
	RecommendedAction_RECOMMEND_CALLBACK_VERIFICATION RecommendedAction = 2
	RecommendedAction_RECOMMEND_MFA_STEP_UP           RecommendedAction = 3
	RecommendedAction_RECOMMEND_SUPERVISOR_ESCALATION RecommendedAction = 4
	RecommendedAction_BLOCK_PENDING_VERIFICATION      RecommendedAction = 5 // only ever set if tenant has opted
)

// Enum value maps for RecommendedAction.
var (
	RecommendedAction_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "PROCEED",
		2: "RECOMMEND_CALLBACK_VERIFICATION",
		3: "RECOMMEND_MFA_STEP_UP",
		4: "RECOMMEND_SUPERVISOR_ESCALATION",
		5: "BLOCK_PENDING_VERIFICATION",
	}
	RecommendedAction_value = map[string]int32{
		"ACTION_UNSPECIFIED":              0,
		"PROCEED":                         1,
		"RECOMMEND_CALLBACK_VERIFICATION": 2,
		"RECOMMEND_MFA_STEP_UP":           3,
		"RECOMMEND_SUPERVISOR_ESCALATION": 4,
		"BLOCK_PENDING_VERIFICATION":      5,
	}
)

func (x RecommendedAction) Enum() *RecommendedAction {
	p := new(RecommendedAction)
	*p = x
	return p
}

func (x RecommendedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_risk_assessment_proto_enumTypes[1].Descriptor()
}

func (RecommendedAction) Type() protoreflect.EnumType {
	return &file_risk_assessment_proto_enumTypes[1]
}

func (x RecommendedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendedAction.Descriptor instead.
func (RecommendedAction) EnumDescriptor() ([]byte, []int) {
	return file_risk_assessment_proto_rawDescGZIP(), []int{1}
}

// One independent evidence signal feeding the fusion engine.
// Each signal is self-describing so the fusion engine (and any human
// auditor) can see not just a number but where it came from and how
// much to trust it.
type RiskSignal struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Score      float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`           // 0.0-1.0, higher = more suspicious
	Confidence float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0-1.0, model's confidence in `score` itself
	Available  bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`    // false if this signal could not be computed
	// (e.g. no enrollment for speaker_match)
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"` // short human-readable reason, for audit/UI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskSignal) Reset() {
	*x = RiskSignal{}
	mi := &file_risk_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskSignal) ProtoMessage() {}

func (x *RiskSignal) ProtoReflect() protoreflect.Message {
	mi := &file_risk_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskSignal.ProtoReflect.Descriptor instead.
func (*RiskSignal) Descriptor() ([]byte, []int) {
	return file_risk_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *RiskSignal) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RiskSignal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RiskSignal) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *RiskSignal) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RiskAssessmentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CallSessionId      string                 `protobuf:"bytes,1,opt,name=call_session_id,json=callSessionId,proto3" json:"call_session_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SynthesisSignal    *RiskSignal            `protobuf:"bytes,3,opt,name=synthesis_signal,json=synthesisSignal,proto3" json:"synthesis_signal,omitempty"`
	SpeakerMatchSignal *RiskSignal            `protobuf:"bytes,4,opt,name=speaker_match_signal,json=speakerMatchSignal,proto3" json:"speaker_match_signal,omitempty"`
	ContextualSignal   *RiskSignal            `protobuf:"bytes,5,opt,name=contextual_signal,json=contextualSignal,proto3" json:"contextual_signal,omitempty"`
	EnrollmentStatus   EnrollmentStatus       `protobuf:"varint,6,opt,name=enrollment_status,json=enrollmentStatus,proto3,enum=voiceintegrity.v1.EnrollmentStatus" json:"enrollment_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RiskAssessmentRequest) Reset() {
	*x = RiskAssessmentRequest{}
	mi := &file_risk_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskAssessmentRequest) ProtoMessage() {}

func (x *RiskAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskAssessmentRequest.ProtoReflect.Descriptor instead.
func (*RiskAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_risk_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *RiskAssessmentRequest) GetCallSessionId() string {
	if x != nil {
		return x.CallSessionId
	}
	return ""
}

func (x *RiskAssessmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RiskAssessmentRequest) GetSynthesisSignal() *RiskSignal {
	if x != nil {
		return x.SynthesisSignal
	}
	return nil
}

func (x *RiskAssessmentRequest) GetSpeakerMatchSignal() *RiskSignal {
	if x != nil {
		return x.SpeakerMatchSignal
	}
	return nil
}

func (x *RiskAssessmentRequest) GetContextualSignal() *RiskSignal {
	if x != nil {
		return x.ContextualSignal
	}
	return nil
}

func (x *RiskAssessmentRequest) GetEnrollmentStatus() EnrollmentStatus {
	if x != nil {
		return x.EnrollmentStatus
	}
	return EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED
}

type RiskAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSessionId string                 `protobuf:"bytes,1,opt,name=call_session_id,json=callSessionId,proto3" json:"call_session_id,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // fused, 0.0-1.0
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                // fused confidence, distinct from risk
	Actions       []RecommendedAction    `protobuf:"varint,4,rep,packed,name=actions,proto3,enum=voiceintegrity.v1.RecommendedAction" json:"actions,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"` // human-readable, built from contributing signals
	EvaluatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	Degraded      bool                   `protobuf:"varint,7,opt,name=degraded,proto3" json:"degraded,omitempty"` // true if computed under fail-safe/partial-signal mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskAssessmentResponse) Reset() {
	*x = RiskAssessmentResponse{}
	mi := &file_risk_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskAssessmentResponse) ProtoMessage() {}

func (x *RiskAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskAssessmentResponse.ProtoReflect.Descriptor instead.
func (*RiskAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_risk_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *RiskAssessmentResponse) GetCallSessionId() string {
	if x != nil {
		return x.CallSessionId
	}
	return ""
}

func (x *RiskAssessmentResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskAssessmentResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RiskAssessmentResponse) GetActions() []RecommendedAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RiskAssessmentResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *RiskAssessmentResponse) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *RiskAssessmentResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

var File_risk_assessment_proto protoreflect.FileDescriptor

const file_risk_assessment_proto_rawDesc = "" +
	"\n" +
	"\x15risk_assessment.proto\x12\x11voiceintegrity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"x\n" +
	"\n" +
	"RiskSignal\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\x95\x03\n" +
	"\x15RiskAssessmentRequest\x12&\n" +
	"\x0fcall_session_id\x18\x01 \x01(\tR\rcallSessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12H\n" +
	"\x10synthesis_signal\x18\x03 \x01(\v2\x1d.voiceintegrity.v1.RiskSignalR\x0fsynthesisSignal\x12O\n" +
	"\x14speaker_match_signal\x18\x04 \x01(\v2\x1d.voiceintegrity.v1.RiskSignalR\x12speakerMatchSignal\x12J\n" +
	"\x11contextual_signal\x18\x05 \x01(\v2\x1d.voiceintegrity.v1.RiskSignalR\x10contextualSignal\x12P\n" +
	"\x11enrollment_status\x18\x06 \x01(\x0e2#.voiceintegrity.v1.EnrollmentStatusR\x10enrollmentStatus\"\xbc\x02\n" +
	"\x16RiskAssessmentResponse\x12&\n" +
	"\x0fcall_session_id\x18\x01 \x01(\tR\rcallSessionId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12>\n" +
	"\aactions\x18\x04 \x03(\x0e2$.voiceintegrity.v1.RecommendedActionR\aactions\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12=\n" +
	"\fevaluated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12\x1a\n" +
	"\bdegraded\x18\a \x01(\bR\bdegraded*m\n" +
	"\x10EnrollmentStatus\x12!\n" +
	"\x1dENROLLMENT_STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fNOT_ENROLLED\x10\x01\x12\f\n" +
	"\bENROLLED\x10\x02\x12\x16\n" +
	"\x12ENROLLMENT_REVOKED\x10\x03*\xbd\x01\n" +
	"\x11RecommendedAction\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPROCEED\x10\x01\x12#\n" +
	"\x1fRECOMMEND_CALLBACK_VERIFICATION\x10\x02\x12\x19\n" +
	"\x15RECOMMEND_MFA_STEP_UP\x10\x03\x12#\n" +
	"\x1fRECOMMEND_SUPERVISOR_ESCALATION\x10\x04\x12\x1e\n" +
	"\x1aBLOCK_PENDING_VERIFICATION\x10\x052q\n" +
	"\x10RiskFusionEngine\x12]\n" +
	"\x06Assess\x12(.voiceintegrity.v1.RiskAssessmentRequest\x1a).voiceintegrity.v1.RiskAssessmentResponseB$Z\"voiceintegrity/v1;voiceintegrityv1b\x06proto3"

var (
	file_risk_assessment_proto_rawDescOnce sync.Once
	file_risk_assessment_proto_rawDescData []byte
)

func file_risk_assessment_proto_rawDescGZIP() []byte {
	file_risk_assessment_proto_rawDescOnce.Do(func() {
		file_risk_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_risk_assessment_proto_rawDesc), len(file_risk_assessment_proto_rawDesc)))
	})
	return file_risk_assessment_proto_rawDescData
}

var file_risk_assessment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_risk_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_risk_assessment_proto_goTypes = []any{
	(EnrollmentStatus)(0),          // 0: voiceintegrity.v1.EnrollmentStatus
	(RecommendedAction)(0),         // 1: voiceintegrity.v1.RecommendedAction
	(*RiskSignal)(nil),             // 2: voiceintegrity.v1.RiskSignal
	(*RiskAssessmentRequest)(nil),  // 3: voiceintegrity.v1.RiskAssessmentRequest
	(*RiskAssessmentResponse)(nil), // 4: voiceintegrity.v1.RiskAssessmentResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_risk_assessment_proto_depIdxs = []int32{
	2, // 0: voiceintegrity.v1.RiskAssessmentRequest.synthesis_signal:type_name -> voiceintegrity.v1.RiskSignal
	2, // 1: voiceintegrity.v1.RiskAssessmentRequest.speaker_match_signal:type_name -> voiceintegrity.v1.RiskSignal
	2, // 2: voiceintegrity.v1.RiskAssessmentRequest.contextual_signal:type_name -> voiceintegrity.v1.RiskSignal
	0, // 3: voiceintegrity.v1.RiskAssessmentRequest.enrollment_status:type_name -> voiceintegrity.v1.EnrollmentStatus
	1, // 4: voiceintegrity.v1.RiskAssessmentResponse.actions:type_name -> voiceintegrity.v1.RecommendedAction
	5, // 5: voiceintegrity.v1.RiskAssessmentResponse.evaluated_at:type_name -> google.protobuf.Timestamp
	3, // 6: voiceintegrity.v1.RiskFusionEngine.Assess:input_type -> voiceintegrity.v1.RiskAssessmentRequest
	4, // 7: voiceintegrity.v1.RiskFusionEngine.Assess:output_type -> voiceintegrity.v1.RiskAssessmentResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_risk_assessment_proto_init() }
func file_risk_assessment_proto_init() {
	if File_risk_assessment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_risk_assessment_proto_rawDesc), len(file_risk_assessment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_assessment_proto_goTypes,
		DependencyIndexes: file_risk_assessment_proto_depIdxs,
		EnumInfos:         file_risk_assessment_proto_enumTypes,
		MessageInfos:      file_risk_assessment_proto_msgTypes,
	}.Build()
	File_risk_assessment_proto = out.File
	file_risk_assessment_proto_goTypes = nil
	file_risk_assessment_proto_depIdxs = nil
}
