// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: risk_assessment.proto

package voiceintegrityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskFusionEngine_Assess_FullMethodName = "/voiceintegrity.v1.RiskFusionEngine/Assess"
)

// RiskFusionEngineClient is the client API for RiskFusionEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskFusionEngineClient interface {
	// Stateless: same inputs always produce the same output. This is a
	// hard requirement, not an implementation detail — see DESIGN.md 4.8
	// on auditability.
	Assess(ctx context.Context, in *RiskAssessmentRequest, opts ...grpc.CallOption) (*RiskAssessmentResponse, error)
}

type riskFusionEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskFusionEngineClient(cc grpc.ClientConnInterface) RiskFusionEngineClient {
	return &riskFusionEngineClient{cc}
}

func (c *riskFusionEngineClient) Assess(ctx context.Context, in *RiskAssessmentRequest, opts ...grpc.CallOption) (*RiskAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskAssessmentResponse)
	err := c.cc.Invoke(ctx, RiskFusionEngine_Assess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskFusionEngineServer is the server API for RiskFusionEngine service.
// All implementations must embed UnimplementedRiskFusionEngineServer
// for forward compatibility.
type RiskFusionEngineServer interface {
	// Stateless: same inputs always produce the same output. This is a
	// hard requirement, not an implementation detail — see DESIGN.md 4.8
	// on auditability.
	Assess(context.Context, *RiskAssessmentRequest) (*RiskAssessmentResponse, error)
	mustEmbedUnimplementedRiskFusionEngineServer()
}

// UnimplementedRiskFusionEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskFusionEngineServer struct{}

func (UnimplementedRiskFusionEngineServer) Assess(context.Context, *RiskAssessmentRequest) (*RiskAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Assess not implemented")
}
func (UnimplementedRiskFusionEngineServer) mustEmbedUnimplementedRiskFusionEngineServer() {}
func (UnimplementedRiskFusionEngineServer) testEmbeddedByValue()                          {}

// UnsafeRiskFusionEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskFusionEngineServer will
// result in compilation errors.
type UnsafeRiskFusionEngineServer interface {
	mustEmbedUnimplementedRiskFusionEngineServer()
}

func RegisterRiskFusionEngineServer(s grpc.ServiceRegistrar, srv RiskFusionEngineServer) {
	// If the following call panics, it indicates UnimplementedRiskFusionEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskFusionEngine_ServiceDesc, srv)
}

func _RiskFusionEngine_Assess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskFusionEngineServer).Assess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskFusionEngine_Assess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskFusionEngineServer).Assess(ctx, req.(*RiskAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskFusionEngine_ServiceDesc is the grpc.ServiceDesc for RiskFusionEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskFusionEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voiceintegrity.v1.RiskFusionEngine",
	HandlerType: (*RiskFusionEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Assess",
			Handler:    _RiskFusionEngine_Assess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk_assessment.proto",
}
